import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { motion } from 'framer-motion';
import { Download, Share2, CornerDownRight } from 'lucide-react';

interface ReportProps {
  report: {
    id: string;
    query: string;
    markdown_content: string;
  };
}

export default function ReportViewer({ report }: ReportProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.7, ease: 'easeOut' }}
      className="overflow-hidden rounded-[1.75rem] border border-fog/60 bg-white shadow-panel"
    >
      <div className="h-1 bg-gradient-to-r from-teal via-blue to-teal" />

      <div className="border-b border-fog/60 bg-white/92 p-8 pb-6">
        <div className="flex justify-between items-start gap-4">
          <div className="space-y-4">
            <div className="flex items-center gap-2 text-sm font-medium text-slate/60">
              <span className="rounded-full border border-teal/15 bg-teal/10 px-3 py-1 text-teal">
                Synthesis Complete
              </span>
              <span className="font-mono">{report.id.split('-')[0]}</span>
            </div>
            <h1 className="font-serif text-3xl font-semibold leading-tight tracking-tight text-ink">
              {report.query}
            </h1>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            <button className="glass-button rounded-xl p-3 group">
              <Share2 className="h-5 w-5 transition-transform group-hover:scale-110" />
            </button>
            <button className="glass-button rounded-xl p-3 group">
              <Download className="h-5 w-5 transition-transform group-hover:scale-110" />
            </button>
          </div>
        </div>
      </div>

      <div className="bg-paper px-8 py-10 md:px-12 md:py-14">
        <div className="report-prose">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>{report.markdown_content}</ReactMarkdown>
        </div>
      </div>

      <div className="flex items-center justify-center gap-2 border-t border-fog/60 bg-white/92 p-6 text-center text-sm text-slate/55">
        <CornerDownRight className="h-4 w-4" />
        Autonomously generated by Meridian Engine
      </div>
    </motion.div>
  );
}
