import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { motion } from 'framer-motion';
import { Download, Share2, CornerDownRight } from 'lucide-react';

interface ReportProps {
  report: {
    id: string;
    query: string;
    markdown_content: string;
  };
}

export default function ReportViewer({ report }: ReportProps) {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.7, ease: 'easeOut' }}
      className="glass rounded-3xl overflow-hidden shadow-2xl relative"
    >
      <div className="absolute top-0 inset-x-0 h-1 bg-gradient-to-r from-accent via-fuchsia-500 to-accent-light" />
      
      {/* Header */}
      <div className="p-8 pb-6 border-b border-white/5 bg-zinc-900/30">
        <div className="flex justify-between items-start gap-4">
          <div className="space-y-4">
            <div className="flex items-center gap-2 text-zinc-400 text-sm font-medium">
              <span className="bg-accent/10 text-accent px-3 py-1 rounded-full border border-accent/20">
                Synthesis Complete
              </span>
              <span className="font-mono">{report.id.split('-')[0]}</span>
            </div>
            <h1 className="text-3xl font-bold text-white leading-tight">
              {report.query}
            </h1>
          </div>
          
          <div className="flex items-center gap-2 shrink-0">
            <button className="glass-button p-3 rounded-xl text-zinc-300 hover:text-white group">
              <Share2 className="w-5 h-5 group-hover:scale-110 transition-transform" />
            </button>
            <button className="glass-button p-3 rounded-xl text-zinc-300 hover:text-white group">
              <Download className="w-5 h-5 group-hover:scale-110 transition-transform" />
            </button>
          </div>
        </div>
      </div>

      {/* Markdown Body */}
      <div className="p-8 md:p-12 max-w-none prose prose-invert prose-lg prose-zinc prose-headings:text-zinc-100 prose-headings:font-bold prose-headings:tracking-tight prose-a:text-accent hover:prose-a:text-accent-light prose-strong:text-zinc-200 prose-li:marker:text-accent">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {report.markdown_content}
        </ReactMarkdown>
      </div>

      <div className="p-6 bg-zinc-900/50 border-t border-white/5 text-center text-sm text-zinc-500 flex items-center justify-center gap-2">
        <CornerDownRight className="w-4 h-4" />
        Autonomously generated by Meridian Engine
      </div>
    </motion.div>
  );
}
